import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  Share,
  Alert,
} from 'react-native';
import { Colors, Typography, Spacing, Radii, Shadows } from '../theme/colors';
import GlassCard from '../components/GlassCard';

// Feature: WhatsApp/SMS Settlement Reminder
// Generates pre-formatted messages and shares via native Share sheet
// Works on both iOS and Android, no external API needed

interface Debt {
  fromName: string;
  toName: string;
  amount: number;
  groupName: string;
  currency: string;
  expenses: string[];
}

interface SettlementReminderScreenProps {
  navigation: any;
  route: {
    params: {
      debts?: Debt[];
    };
  };
}

const MOCK_DEBTS: Debt[] = [
  {
    fromName: 'Rahul',
    toName: 'You',
    amount: 850,
    groupName: 'Goa Trip ???',
    currency: '?',
    expenses: ['Hotel booking', 'Dinner at Beach Shack', 'Taxi'],
  },
  {
    fromName: 'Priya',
    toName: 'You',
    amount: 420,
    groupName: 'Office Lunch ??',
    currency: '?',
    expenses: ['Lunch delivery', 'Chai'],
  },
];

const SettlementReminderScreen: React.FC<SettlementReminderScreenProps> = ({
  navigation,
  route,
}) => {
  const debts = route?.params?.debts || MOCK_DEBTS;
  const totalOwed = debts.reduce((sum, d) => sum + d.amount, 0);

  const generateWhatsAppMessage = (debt: Debt): string => {
    const expenseList = debt.expenses.map(e => `  • ${e}`).join('\n');
    return `Hi ${debt.fromName}! ??\n\nJust a friendly reminder about our shared expenses from *${debt.groupName}*:\n\n${expenseList}\n\n?? *Total you owe: ${debt.currency}${debt.amount.toFixed(2)}*\n\nYou can pay me via:\n?? UPI: mohit@paytm\n\nPlease settle when you get a chance! Thanks ??\n\n_Sent via WealthTrack_`;
  };

  const generateBulkMessage = (): string => {
    const lines = debts.map(
      d => `• ${d.fromName}: ${d.currency}${d.amount.toFixed(2)} (${d.groupName})`
    );
    return `?? *Settlement Summary*\n\nThe following people owe me money:\n\n${lines.join('\n')}\n\n?? *Total: ${debts[0]?.currency || '?'}${totalOwed.toFixed(2)}*\n\nPlease pay via UPI: mohit@paytm\n\n_Generated by WealthTrack_`;
  };

  const shareReminder = async (debt: Debt) => {
    const message = generateWhatsAppMessage(debt);
    try {
      await Share.share({
        message,
        title: `Payment Reminder — ${debt.fromName}`,
      });
    } catch {
      Alert.alert('Error', 'Could not open share sheet');
    }
  };

  const shareBulkReminder = async () => {
    const message = generateBulkMessage();
    try {
      await Share.share({
        message,
        title: 'WealthTrack — Settlement Summary',
      });
    } catch {
      Alert.alert('Error', 'Could not open share sheet');
    }
  };

  const copyToClipboard = (debt: Debt) => {
    // In real app: Clipboard.setString(generateWhatsAppMessage(debt))
    Alert.alert('Copied!', 'Message copied to clipboard');
  };

  return (
    <View style={styles.container}>
      <ScrollView showsVerticalScrollIndicator={false}>
        {/* Header */}
        <View style={styles.header}>
          <TouchableOpacity style={styles.backBtn} onPress={() => navigation.goBack()}>
            <Text style={styles.backIcon}>?</Text>
          </TouchableOpacity>
          <Text style={styles.title}>Send Reminders</Text>
          <View style={{ width: 44 }} />
        </View>

        {/* Summary Banner */}
        <GlassCard style={styles.summaryCard} variant="accent">
          <View style={styles.summaryRow}>
            <View>
              <Text style={styles.summaryLabel}>Total Pending</Text>
              <Text style={styles.summaryAmount}>?{totalOwed.toFixed(2)}</Text>
            </View>
            <Text style={styles.summaryEmoji}>??</Text>
          </View>
          <Text style={styles.summarySubtitle}>
            {debts.length} {debts.length === 1 ? 'person owes' : 'people owe'} you money
          </Text>
          {/* Bulk share button */}
          <TouchableOpacity style={styles.bulkShareBtn} onPress={shareBulkReminder}>
            <Text style={styles.bulkShareIcon}>??</Text>
            <Text style={styles.bulkShareText}>Share All Reminders</Text>
          </TouchableOpacity>
        </GlassCard>

        {/* Individual Debt Cards */}
        <Text style={styles.sectionTitle}>Individual Reminders</Text>
        {debts.map((debt, idx) => (
          <GlassCard key={idx} style={styles.debtCard} variant="default">
            {/* Person Info */}
            <View style={styles.debtHeader}>
              <View style={styles.avatarRow}>
                <View style={styles.avatar}>
                  <Text style={styles.avatarText}>
                    {debt.fromName.charAt(0).toUpperCase()}
                  </Text>
                </View>
                <View>
                  <Text style={styles.debtPersonName}>{debt.fromName}</Text>
                  <Text style={styles.debtGroup}>{debt.groupName}</Text>
                </View>
              </View>
              <View style={styles.debtAmountBadge}>
                <Text style={styles.debtAmountText}>
                  {debt.currency}{debt.amount.toFixed(2)}
                </Text>
              </View>
            </View>

            {/* Expense List */}
            <View style={styles.expenseList}>
              {debt.expenses.map((exp, i) => (
                <View key={i} style={styles.expenseRow}>
                  <Text style={styles.expenseDot}>?</Text>
                  <Text style={styles.expenseName}>{exp}</Text>
                </View>
              ))}
            </View>

            {/* Message Preview */}
            <View style={styles.messagePreview}>
              <Text style={styles.previewLabel}>Message Preview</Text>
              <Text style={styles.previewText} numberOfLines={4}>
                {generateWhatsAppMessage(debt)}
              </Text>
            </View>

            {/* Action Buttons */}
            <View style={styles.actionRow}>
              <TouchableOpacity
                style={styles.copyBtn}
                onPress={() => copyToClipboard(debt)}
              >
                <Text style={styles.copyBtnText}>?? Copy</Text>
              </TouchableOpacity>
              <TouchableOpacity
                style={styles.shareBtn}
                onPress={() => shareReminder(debt)}
              >
                <Text style={styles.shareBtnIcon}>??</Text>
                <Text style={styles.shareBtnText}>Share via WhatsApp / SMS</Text>
              </TouchableOpacity>
            </View>
          </GlassCard>
        ))}

        {/* UPI Quick Pay Note */}
        <GlassCard style={styles.tipCard} padding={12}>
          <Text style={styles.tipTitle}>?? Quick Settle Tips</Text>
          <Text style={styles.tipText}>
            • Share your UPI ID or QR code in the message{'\n'}
            • Messages include expense breakdown for context{'\n'}
            • Mark as settled manually after payment received
          </Text>
        </GlassCard>

        <View style={{ height: 80 }} />
      </ScrollView>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.bg,
    paddingHorizontal: Spacing.md,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 60,
    paddingBottom: Spacing.md,
  },
  backBtn: {
    width: 44,
    height: 44,
    borderRadius: Radii.full,
    backgroundColor: Colors.glass,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Colors.glassBorder,
  },
  backIcon: { fontSize: 20, color: Colors.textPrimary },
  title: {
    fontSize: Typography.sizes.xl,
    fontFamily: Typography.fontFamily.bold,
    color: Colors.textPrimary,
  },
  summaryCard: {
    marginBottom: Spacing.lg,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  summaryLabel: {
    fontSize: Typography.sizes.xs,
    color: Colors.textMuted,
    fontFamily: Typography.fontFamily.medium,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  summaryAmount: {
    fontSize: Typography.sizes.xxl,
    fontFamily: Typography.fontFamily.bold,
    color: Colors.textPrimary,
    marginTop: 2,
  },
  summaryEmoji: { fontSize: 36 },
  summarySubtitle: {
    fontSize: Typography.sizes.sm,
    color: Colors.textSecondary,
    fontFamily: Typography.fontFamily.regular,
    marginBottom: Spacing.md,
  },
  bulkShareBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.primary,
    borderRadius: Radii.md,
    paddingVertical: 12,
    gap: 8,
    ...Shadows.fab,
  },
  bulkShareIcon: { fontSize: 18 },
  bulkShareText: {
    fontSize: Typography.sizes.md,
    color: Colors.textPrimary,
    fontFamily: Typography.fontFamily.semiBold,
  },
  sectionTitle: {
    fontSize: Typography.sizes.md,
    fontFamily: Typography.fontFamily.semiBold,
    color: Colors.textPrimary,
    marginBottom: Spacing.sm,
  },
  debtCard: {
    marginBottom: Spacing.md,
    gap: Spacing.sm,
  },
  debtHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  avatarRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: Colors.glassStrong,
    borderWidth: 2,
    borderColor: Colors.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    fontSize: Typography.sizes.md,
    color: Colors.primaryLight,
    fontFamily: Typography.fontFamily.bold,
  },
  debtPersonName: {
    fontSize: Typography.sizes.md,
    color: Colors.textPrimary,
    fontFamily: Typography.fontFamily.semiBold,
  },
  debtGroup: {
    fontSize: Typography.sizes.xs,
    color: Colors.textMuted,
    fontFamily: Typography.fontFamily.regular,
  },
  debtAmountBadge: {
    backgroundColor: 'rgba(244,63,94,0.15)',
    borderRadius: Radii.md,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: Colors.negative,
  },
  debtAmountText: {
    fontSize: Typography.sizes.md,
    color: Colors.negative,
    fontFamily: Typography.fontFamily.bold,
  },
  expenseList: {
    gap: 4,
    paddingLeft: 4,
    borderLeftWidth: 2,
    borderLeftColor: Colors.bgCardBorder,
    paddingVertical: 4,
    marginLeft: 4,
  },
  expenseRow: {
    flexDirection: 'row',
    gap: 6,
    alignItems: 'center',
  },
  expenseDot: {
    color: Colors.accent,
    fontSize: 10,
  },
  expenseName: {
    fontSize: Typography.sizes.sm,
    color: Colors.textSecondary,
    fontFamily: Typography.fontFamily.regular,
  },
  messagePreview: {
    backgroundColor: Colors.bgInput,
    borderRadius: Radii.md,
    padding: Spacing.sm,
    borderWidth: 1,
    borderColor: Colors.glassBorder,
  },
  previewLabel: {
    fontSize: Typography.sizes.xs,
    color: Colors.textMuted,
    fontFamily: Typography.fontFamily.medium,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 6,
  },
  previewText: {
    fontSize: Typography.sizes.xs,
    color: Colors.textSecondary,
    fontFamily: Typography.fontFamily.regular,
    lineHeight: 16,
  },
  actionRow: {
    flexDirection: 'row',
    gap: Spacing.sm,
  },
  copyBtn: {
    paddingHorizontal: Spacing.md,
    paddingVertical: 10,
    backgroundColor: Colors.glass,
    borderRadius: Radii.md,
    borderWidth: 1,
    borderColor: Colors.glassBorder,
  },
  copyBtnText: {
    fontSize: Typography.sizes.sm,
    color: Colors.textSecondary,
    fontFamily: Typography.fontFamily.medium,
  },
  shareBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.accent,
    borderRadius: Radii.md,
    paddingVertical: 10,
    gap: 6,
    ...Shadows.glow,
  },
  shareBtnIcon: { fontSize: 16 },
  shareBtnText: {
    fontSize: Typography.sizes.sm,
    color: Colors.textInverse,
    fontFamily: Typography.fontFamily.semiBold,
  },
  tipCard: {
    marginTop: Spacing.sm,
    gap: 6,
  },
  tipTitle: {
    fontSize: Typography.sizes.sm,
    color: Colors.textSecondary,
    fontFamily: Typography.fontFamily.semiBold,
    marginBottom: 4,
  },
  tipText: {
    fontSize: Typography.sizes.xs,
    color: Colors.textMuted,
    fontFamily: Typography.fontFamily.regular,
    lineHeight: 18,
  },
});

export default SettlementReminderScreen;
